[package]
name = "tree-sitter-xml"
description = "XML grammar for tree-sitter"
version = "0.0.1"
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "dtd", "xml"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/ObserverOfTime/tree-sitter-xml"
edition = "2021"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust",
  "dtd/grammar.js",
  "dtd/src",
  "dtd/queries",
  "xml/grammar.js",
  "xml/src",
  "xml/queries",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = ">= 0.19, < 0.21"

[build-dependencies]
cc = "1.0"
